/**
 * Scenario catalog — shared metadata for HTML/Markdown reports and documentation.
 */

export const SCENARIO_CATALOG = {
  smoke: {
    script: 'scenarios/smoke/api-health.js',
    npmScript: 'test:smoke',
    type: 'Smoke',
    profile: 'smoke',
    ciReport: true,
    description: 'Minimal VUs — availability gate and baseline API latency.',
    flow: 'GET /health → GET /api/users → POST /api/auth/login per iteration.',
    endpoints: ['GET /health', 'GET /api/users', 'POST /api/auth/login'],
    customMetrics: [],
    thresholdProfile: 'smoke',
  },
  'load-auth': {
    script: 'scenarios/load/api-auth.js',
    npmScript: 'test:load:auth',
    type: 'Load',
    profile: 'smoke (report) / load (default)',
    ciReport: true,
    description: 'Sustained login throughput — auth bottleneck detection.',
    flow: 'POST /api/auth/login with token validation each iteration.',
    endpoints: ['POST /api/auth/login'],
    customMetrics: ['login_duration p(95)<2000', 'login_errors rate<0.01'],
    thresholdProfile: 'load',
  },
  'load-users': {
    script: 'scenarios/load/api-users.js',
    npmScript: 'test:load:users',
    type: 'Load',
    profile: 'smoke (report) / load (default)',
    ciReport: true,
    description: 'Read-heavy users list with token reuse via setup().',
    flow: 'setup: login once → GET /api/users (authenticated) per iteration.',
    endpoints: ['POST /api/auth/login', 'GET /api/users'],
    customMetrics: ['users_list_duration p(95)<2000'],
    thresholdProfile: 'load',
  },
  'mixed-traffic': {
    script: 'scenarios/load/mixed-traffic.js',
    npmScript: 'test:load:mixed',
    type: 'Load',
    profile: 'smoke (report) / load (default)',
    ciReport: true,
    description: 'Realistic weighted mix of API and static page traffic.',
    flow: 'Login → weighted pick: 35% health, 30% users (auth), 15% static, 20% users (anon).',
    endpoints: [
      'GET /health',
      'GET /api/users',
      'POST /api/auth/login',
      'GET /web/login.html',
      'GET /web/dashboard.html',
      'GET /web/team.html',
      'GET /web/settings.html',
      'GET /web/activity.html',
    ],
    customMetrics: ['mixed_request_duration'],
    thresholdProfile: 'load',
  },
  'login-flow': {
    script: 'journeys/login-flow.js',
    npmScript: 'test:journey:login',
    type: 'Journey',
    profile: 'smoke (report) / load (default)',
    ciReport: true,
    description: 'HTTP user journey — login page → API login → dashboard.',
    flow: 'Group 01: GET login.html → Group 02: POST login → Group 03: GET dashboard.html.',
    endpoints: ['GET /web/login.html', 'POST /api/auth/login', 'GET /web/dashboard.html'],
    customMetrics: ['login_flow_duration p(95)<4000'],
    thresholdProfile: 'load',
  },
  'authenticated-user': {
    script: 'journeys/authenticated-user.js',
    npmScript: 'test:journey:auth',
    type: 'Journey',
    profile: 'smoke (report) / load (default)',
    ciReport: true,
    description: 'Authenticated session — login → users → browse dashboard and team.',
    flow: 'Login → GET /api/users → GET dashboard.html → GET team.html.',
    endpoints: [
      'POST /api/auth/login',
      'GET /api/users',
      'GET /web/dashboard.html',
      'GET /web/team.html',
    ],
    customMetrics: ['journey_duration'],
    thresholdProfile: 'load',
  },
  spike: {
    script: 'scenarios/spike/api-spike.js',
    npmScript: 'test:spike',
    type: 'Spike',
    profile: 'spike',
    ciReport: true,
    description: 'Sudden burst (5→100 VUs) — validates recovery under spike.',
    flow: 'GET /health → login → GET /api/users with minimal think time.',
    endpoints: ['GET /health', 'POST /api/auth/login', 'GET /api/users'],
    customMetrics: ['spike_failures rate<0.10'],
    thresholdProfile: 'stress',
  },
  stress: {
    script: 'scenarios/stress/api-breakpoint.js',
    npmScript: 'test:stress',
    type: 'Stress',
    profile: 'stress / breakpoint',
    ciReport: false,
    description: 'Ramp beyond normal load to find degradation and capacity ceiling.',
    flow: 'Health + login + users; counts degraded_responses when latency exceeds limits.',
    endpoints: ['GET /health', 'POST /api/auth/login', 'GET /api/users'],
    customMetrics: ['degraded_responses'],
    thresholdProfile: 'stress',
  },
  soak: {
    script: 'scenarios/soak/api-endurance.js',
    npmScript: 'test:soak',
    type: 'Soak',
    profile: 'soak (K6_SOAK_MINUTES, default 30)',
    ciReport: false,
    description: 'Long steady load — detect memory leaks and latency drift.',
    flow: 'Health + login + users with think time over extended steady state.',
    endpoints: ['GET /health', 'POST /api/auth/login', 'GET /api/users'],
    customMetrics: ['soak_latency'],
    thresholdProfile: 'soak',
  },
  browser: {
    script: 'scenarios/browser/login-page.js',
    npmScript: 'test:browser:login',
    type: 'Browser',
    profile: 'smoke thresholds + browser_page_load',
    ciReport: false,
    description: 'k6 browser module — login page with Chromium (requires native k6).',
    flow: 'Navigate login.html → fill data-testid fields → submit → wait.',
    endpoints: ['GET /web/login.html'],
    customMetrics: ['browser_lcp', 'browser_page_load p(95)<5000'],
    thresholdProfile: 'smoke',
  },
};

export const SHARED_CHECKS = [
  'health status 200',
  'health responds quickly (< 1s)',
  'users status 200',
  'users has array (non-empty)',
  'users responds within 2s',
  'static page status 200',
  'static page has html content-type',
  'login 200 + token present',
];

export const THRESHOLD_PROFILES = {
  smoke: {
    http_req_failed: 'rate < 0.5%',
    http_req_duration: 'p(95) < 1500 ms, avg < 800 ms',
    'http_req_duration{endpoint:health}': 'p(95) < 500 ms',
    'http_req_duration{endpoint:users}': 'p(95) < 1500 ms',
    'http_req_duration{endpoint:auth_login}': 'p(95) < 2000 ms',
    checks: 'rate > 99%',
  },
  load: {
    http_req_failed: 'rate < 1%',
    http_req_duration: 'p(95) < 2500 ms, p(99) < 6000 ms',
    'http_req_duration{endpoint:health}': 'p(95) < 800 ms',
    'http_req_duration{endpoint:users}': 'p(95) < 2000 ms',
    'http_req_duration{endpoint:auth_login}': 'p(95) < 3000 ms',
    checks: 'rate > 98%',
  },
  stress: {
    http_req_failed: 'rate < 5%',
    http_req_duration: 'p(95) < 5000 ms',
    checks: 'rate > 95%',
  },
  soak: {
    http_req_failed: 'rate < 0.5%',
    http_req_duration: 'p(95) < 2500 ms, avg < 1200 ms',
    checks: 'rate > 99%',
  },
};
